local md = require("codetour.markdown")

describe("codetour.markdown.extract_links", function()
  it("extracts a step ref [#3]", function()
    local out = md.extract_links("see [#3] for details")
    assert.equals(1, #out)
    assert.equals("step_ref", out[1].kind)
    assert.equals(3, out[1].step)
  end)

  it("extracts a labeled step ref [label][#2]", function()
    local out = md.extract_links("[click here][#2]")
    assert.equals(1, #out)
    assert.equals("step_ref", out[1].kind)
    assert.equals(2, out[1].step)
    assert.equals("click here", out[1].label)
  end)

  it("extracts a shell command line >> npm test", function()
    local out = md.extract_links(">> npm test")
    assert.equals(1, #out)
    assert.equals("shell", out[1].kind)
    assert.equals("npm test", out[1].command)
  end)

  it("extracts a command link [Run](command:foo.bar)", function()
    local out = md.extract_links("[Run](command:foo.bar)")
    assert.equals(1, #out)
    assert.equals("command", out[1].kind)
    assert.equals("foo.bar", out[1].command)
  end)

  it("returns empty for plain text", function()
    assert.same({}, md.extract_links("plain *bold* text"))
  end)
end)
