local recorder = require("codetour.recorder")
local state = require("codetour.state")
local loader = require("codetour.loader")

describe("codetour.recorder", function()
  local tmp_tours_dir
  local tmp_project

  before_each(function()
    state.reset()
    tmp_tours_dir = vim.fn.tempname()
    tmp_project = vim.fn.tempname()
    vim.fn.mkdir(tmp_tours_dir, "p")
    vim.fn.mkdir(tmp_project, "p")
    require("codetour").setup({ tours_dir = tmp_tours_dir })
  end)

  it("new_tour creates a fresh tour file in tours_dir with projectRoot from cwd", function()
    vim.cmd("cd " .. tmp_project)
    local tour = recorder.new_tour({ title = "My Tour", description = "desc" })
    assert.equals("My Tour", tour.title)
    assert.equals(0, #tour.steps)
    assert.matches(tmp_tours_dir .. "/my%-tour%.tour$", tour._path)
    assert.is_string(tour.projectRoot)
    local on_disk = loader.load(tour._path)
    assert.equals("My Tour", on_disk.title)
    assert.equals(tour.projectRoot, on_disk.projectRoot)
  end)

  it("add_step computes file path relative to tour.projectRoot", function()
    vim.cmd("cd " .. tmp_project)
    local tour = recorder.new_tour({ title = "T" })
    local sample = tmp_project .. "/sub/sample.lua"
    vim.fn.mkdir(tmp_project .. "/sub", "p")
    vim.fn.writefile({ "a", "b", "c", "d" }, sample)
    vim.cmd("edit " .. sample)
    vim.api.nvim_win_set_cursor(0, { 3, 0 })

    recorder.add_step({ title = "myMarker", description = "explain c" })
    local refreshed = loader.load(tour._path)
    assert.equals(1, #refreshed.steps)
    assert.equals("sub/sample.lua", refreshed.steps[1].file)
    assert.equals(3, refreshed.steps[1].line)
    assert.equals("explain c", refreshed.steps[1].description)
    assert.equals("myMarker", refreshed.steps[1].title)
    assert.equals(0, refreshed.steps[1].depth)
  end)

  it("add_step accepts string for backward compat", function()
    vim.cmd("cd " .. tmp_project)
    local tour = recorder.new_tour({ title = "T" })
    local sample = tmp_project .. "/x.lua"
    vim.fn.writefile({ "a" }, sample)
    vim.cmd("edit " .. sample)
    recorder.add_step("just desc")
    local refreshed = loader.load(tour._path)
    assert.equals("just desc", refreshed.steps[1].description)
    assert.is_nil(refreshed.steps[1].title)
  end)

  it("add_step respects depth option", function()
    vim.cmd("cd " .. tmp_project)
    local tour = recorder.new_tour({ title = "T" })
    local sample = tmp_project .. "/x.lua"
    vim.fn.writefile({ "a" }, sample)
    vim.cmd("edit " .. sample)
    recorder.add_step({ description = "d", depth = 2 })
    local refreshed = loader.load(tour._path)
    assert.equals(2, refreshed.steps[1].depth)
  end)

  it("add_step rejects buffer outside projectRoot", function()
    vim.cmd("cd " .. tmp_project)
    recorder.new_tour({ title = "T" })
    local outside = vim.fn.tempname() .. ".lua"
    vim.fn.writefile({ "x" }, outside)
    vim.cmd("edit " .. outside)
    local ok, err = pcall(recorder.add_step, { description = "should fail" })
    assert.is_false(ok)
    assert.matches("outside projectRoot", err)
  end)

  describe("anchor", function()
    local sample

    before_each(function()
      vim.cmd("cd " .. tmp_project)
      sample = tmp_project .. "/a.lua"
      vim.fn.writefile({ "a", "b", "c", "d" }, sample)
      vim.cmd("edit " .. sample)
    end)

    it("anchor=nil appends to end (default)", function()
      local tour = recorder.new_tour({ title = "A" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      recorder.add_step({ description = "s1" })
      vim.api.nvim_win_set_cursor(0, { 2, 0 })
      recorder.add_step({ description = "s2" })
      vim.api.nvim_win_set_cursor(0, { 3, 0 })
      recorder.add_step({ description = "s3" })
      assert.equals(3, #tour.steps)
      assert.equals("s1", tour.steps[1].description)
      assert.equals("s2", tour.steps[2].description)
      assert.equals("s3", tour.steps[3].description)
      assert.is_nil(state.get_anchor())
    end)

    it("set_anchor(1) inserts next step at index 2", function()
      local tour = recorder.new_tour({ title = "B" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      recorder.add_step({ description = "s1" })
      vim.api.nvim_win_set_cursor(0, { 2, 0 })
      recorder.add_step({ description = "s2" })
      state.set_anchor(1)
      vim.api.nvim_win_set_cursor(0, { 3, 0 })
      recorder.add_step({ description = "inserted" })
      assert.equals(3, #tour.steps)
      assert.equals("s1", tour.steps[1].description)
      assert.equals("inserted", tour.steps[2].description)
      assert.equals("s2", tour.steps[3].description)
      assert.equals(2, state.get_anchor())
    end)

    it("anchor auto advances after each insert", function()
      local tour = recorder.new_tour({ title = "C" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      recorder.add_step({ description = "s1" })
      vim.api.nvim_win_set_cursor(0, { 2, 0 })
      recorder.add_step({ description = "s2" })
      vim.api.nvim_win_set_cursor(0, { 3, 0 })
      recorder.add_step({ description = "s3" })
      state.set_anchor(1)
      vim.api.nvim_win_set_cursor(0, { 4, 0 })
      recorder.add_step({ description = "i1" })
      assert.equals(2, state.get_anchor())
      recorder.add_step({ description = "i2" })
      assert.equals(3, state.get_anchor())
      assert.equals(5, #tour.steps)
      assert.equals("s1", tour.steps[1].description)
      assert.equals("i1", tour.steps[2].description)
      assert.equals("i2", tour.steps[3].description)
      assert.equals("s2", tour.steps[4].description)
      assert.equals("s3", tour.steps[5].description)
    end)

    it("anchor clears when insert advances to last position", function()
      local tour = recorder.new_tour({ title = "D" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      recorder.add_step({ description = "s1" })
      vim.api.nvim_win_set_cursor(0, { 2, 0 })
      recorder.add_step({ description = "s2" })
      state.set_anchor(1)
      vim.api.nvim_win_set_cursor(0, { 3, 0 })
      recorder.add_step({ description = "inserted" })
      assert.equals(3, #tour.steps)
      assert.equals(2, state.get_anchor())
      recorder.add_step({ description = "last_insert" })
      assert.equals(4, #tour.steps)
      assert.equals("s1", tour.steps[1].description)
      assert.equals("inserted", tour.steps[2].description)
      assert.equals("last_insert", tour.steps[3].description)
      assert.equals("s2", tour.steps[4].description)
      assert.equals(3, state.get_anchor())
    end)

    it("set_anchor out of range clears anchor", function()
      recorder.new_tour({ title = "E" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      recorder.add_step({ description = "s1" })
      state.set_anchor(99)
      assert.is_nil(state.get_anchor())
    end)

    it("clear_anchor reverts to append mode", function()
      local tour = recorder.new_tour({ title = "F" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      recorder.add_step({ description = "s1" })
      vim.api.nvim_win_set_cursor(0, { 2, 0 })
      recorder.add_step({ description = "s2" })
      state.set_anchor(1)
      state.clear_anchor()
      vim.api.nvim_win_set_cursor(0, { 3, 0 })
      recorder.add_step({ description = "appended" })
      assert.equals(3, #tour.steps)
      assert.equals("appended", tour.steps[3].description)
    end)
  end)
end)
